# Make sure that ntpd is removed
# Having two NTP servers installed can cause synchronisation issues
#
- name: Remove ntp package if present
  yum:
    name: ntp
    state: removed
  when: ntp_chrony_remove_ntpd == true
  tags: [ntp, chrony]



# Install chrony service
#
- name: Install chrony
  yum:
    name: chrony
    state: latest
  tags: [ntp, chrony]



# Set servers that chrony will sync with
#
- name: Add servers to sync with
  lineinfile:
    dest: /etc/chrony.conf
    line: "server {{ item }} iburst"
    state: present
  with_items: "{{ ntp_chrony_servers }}"
  notify: restart chronyd
  tags: [ntp, chrony]

- name: Remove all other servers
  lineinfile:
    dest: /etc/chrony.conf
    regexp: "server (?!{{ ntp_chrony_servers | join('|') |  replace('.','\\.') }})"
    state: absent
  notify: restart chronyd
  tags: [ntp, chrony]



# Make sure that chronyd service is started and enabled on boot
#
- name: Start chrony service
  service:
    name: chronyd
    state: started
    enabled: yes
  tags: [ntp, chrony, healthcheck]
