# Check if MongoDB is installed or not and if it should be updated or not
#
- name: Check if MongoDB is installed
  command: mongod --version warn=no
  register: mongodb_is_installed_test
  ignore_errors: yes
  changed_when: false
  tags: [mongodb]

- set_fact:
    mongodb_is_installed: true
  when: mongodb_is_installed_test.rc != 2
  tags: [mongodb]

- set_fact:
    mongodb_is_installed: false
    mongodb_install_new_version: true
  when: mongodb_is_installed_test.rc == 2
  tags: [mongodb]

- set_fact:
    mongodb_install_new_version: true
  when: ( mongodb_is_installed == true ) and ( mongodb_is_installed_test.stdout_lines[0] | replace('db version v','') != mongodb_version )
  tags: [mongodb]

- set_fact:
    mongodb_install_new_version: false
  when: ( mongodb_is_installed == true ) and ( mongodb_is_installed_test.stdout_lines[0] | replace('db version v','') == mongodb_version )
  tags: [mongodb]



# Install/Update MongoDB to desired version
# These tasks will be executed when
#  1. MongoDB is not installed
#  2. MongoDB is installed but not in desired version
#
- include: install.yml
  when: "mongodb_install_new_version == true and mongodb_manage_installation == true"



# Configure MongoDB
#
- include: configure.yml
  when: "mongodb_manage_configuration == true"



# Make sure that mongod service is started and enabled on boot
#
- name: Start and enable MongoDB service
  service:
    name: mongod
    state: started
    enabled: yes
  tags: [mongodb, healthcheck]
