# Create a dump with list of all available groups
# This task will execute only once
# Like in packages, it's useful to have initial list of groups on fresh system
#
- name: Dump available groups
  shell: "getent group > {{ centos_groups_initial_groups_list_path }}"
  args:
    creates: "{{ centos_groups_initial_groups_list_path }}"
  tags: [centos, groups]



# Remove the groups from the server you don't need
#
- name: Remove groups from system
  group:
    name: "{{ item }}"
    state: absent
  with_items: "{{ centos_groups_to_remove }}"
  tags: [centos, groups]



# Make sure that following groups are available in the system
#
- name: Create groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ centos_groups_available }}"
  tags: [centos, groups]
