# Make sure that logrotate is installed in latest version
#
- name: Install logrotate
  yum:
    name: logrotate
    state: latest
  tags: [centos, logrotate]



# Install logrotate scripts
# Each script should be placed in separate file
#
- name: Install logrotate scripts
  template:
    src: logrotate.j2
    dest: "/etc/logrotate.d/{{ item.name }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ centos_logrotate_scripts }}"
  when: centos_logrotate_scripts is defined
  tags: [centos, logrotate]
