# Users in wheel group has access to sudo command.
# However you can have two different approaches here
# First one is for lazy people and is to make all commands available without providing password after calling sudo command
# It is also less secure. If someone has access to user with wheel group and password is not required, he basically has access to root account and can do whatever he wants
# Second option is to require user password after sudo command
# It's less convenient but it increases security
- name: Enable sudo usage that requires password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) ALL"
  when: "centos_groups_wheel_password_required == true"
  tags: [centos, sudo]

- name: Enable sudo usage that does not require password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
  when: "centos_groups_wheel_password_required == false"
  tags: [centos, sudo]
