# Export list of available users to file
# This task will be executed only once.
# It's useful to have such list available on the system later on, when you want to check if given user was present in the system etc.
#
- name: Dump available users
  shell: "getent passwd > {{ centos_users_initial_users_list_path }}"
  args:
    creates: "{{ centos_users_initial_users_list_path }}"
  tags: [centos, users]



# Remove given users from the system
#
- name: Remove users
  user:
    name: "{{ item }}"
    state: absent
  with_items: "{{ centos_users_to_remove }}"
  tags: [centos, users]



# Make sure that following users are available in the system
#
- name: Create users
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups }}"
    password: "{{ item.password }}"
    append: true
    state: present
    generate_ssh_key: "{{ item.generate_ssh_key }}"
    ssh_key_bits: 4096
  with_items: "{{ centos_users_available }}"
  tags: [centos, users]



# Add authorised keys to user
# It's useful when you want to add SSH key which you can connect to given user
#
- name: Add authorized keys to users
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup( 'file', item.path_to_file ) }}"
  with_items: "{{ centos_users_authorized_keys }}"
  tags: [centos, users]
