# Create a dump with list of all installed packages
# This task will execute only once
# Sometimes it's really useful to have an overview of fresh system packages
# warn=no is for suppresing Ansible warning about not using yum module
#
- name: Dump installed packages
  shell: "yum list installed > {{ centos_yum_initial_package_list_path }} warn=no"
  args:
    creates: "{{ centos_yum_initial_package_list_path }}"
  tags: [centos, yum]



# Make sure that gpgcheck is enabled in Yum configuration.
# You should always check package signature before it's installation.
#
- name: Make sure that GPG check is enabled
  lineinfile:
    dest: /etc/yum.conf
    line: "gpgcheck=1"
    state: present
  tags: [centos, yum]



# Make sure that gpgcheck is enabled in all repositories
# This is the same check as above, but for all repo files in /etc/yum.repos.d directory
- name: Get all repositories
  shell: find /etc/yum.repos.d -type f -name "*.repo" warn=no
  register: centos_yum_repositories
  changed_when: false
  tags: [centos, yum]

- name: Make sure that GPG check is enabled in all repositories
  lineinfile:
    dest: "{{ item }}"
    line: gpgcheck=0
    state: absent
  with_items: "{{ centos_yum_repositories.stdout_lines }}"
  tags: [centos, yum]