# Create a dump with list of all installed packages
# This task will execute only once
# Sometimes it's really useful to have an overview of fresh system packages
# warn=no is for suppresing Ansible warning about not using yum module
#
- name: Dump installed packages
  shell: "yum list installed > {{ centos_yum_initial_package_list_path }} warn=no"
  args:
    creates: "{{ centos_yum_initial_package_list_path }}"



# Make sure that gpgcheck is enabled in Yum configuration.
# You should always check package signature before it's installation.
#
- name: Make sure that GPG check is enabled
  lineinfile:
    dest: /etc/yum.conf
    line: "gpgcheck=1"
    state: present
