####### CHOOSE IF THIS ROLE SHOULD EXECUTE TASKS FROM GIVEN GROUPS #######

# Should this role use install tasks for compiling nginx?
nginx_manage_installation: yes

# Should this role use configure tasks for configuring nginx?
nginx_manage_configuration: yes





####### INSTALL TASKS CONFIGURATION #######

# Version of nginx that should be present in the system
nginx_version: "1.13.4"

# Path where nginx will be installed. NO trailing slash at the end!
nginx_install_path: /usr/local/nginx

# Location of files for nginx sources
nginx_sources_location: /usr/src

# User that will build nginx. Please never use root account for compiling software. It can lead to serious security issues
nginx_build_user: vagrant

# Group of the build user.
nginx_build_group: vagrant

# List of configuration options for nginx
nginx_configure_options:
  - "--prefix={{ nginx_install_path }}"
  - --with-pcre-jit
  - --without-http_charset_module
  - --without-http_ssi_module
  - --without-http_userid_module
  - --without-http_auth_basic_module
  - --without-http_autoindex_module
  - --without-http_geo_module
  - --without-http_map_module
  - --without-http_split_clients_module
  - --without-http_referer_module
  - --without-http_fastcgi_module
  - --without-http_uwsgi_module
  - --without-http_scgi_module
  - --without-http_memcached_module
  - --without-http_limit_conn_module
  - --without-http_limit_req_module
  - --without-http_browser_module
  - --with-threads
  - --with-file-aio
  - --with-http_ssl_module
  - --with-openssl=/usr/src/openssl-OpenSSL_1_1_0f
  - --with-http_v2_module
  - --with-http_stub_status_module

# Remove downloaded sources after installation
nginx_cleanup_after_install: yes





####### CONFIGURE TASKS CONFIGURATION #######

# nginx.conf path
nginx_conf_path: "{{ nginx_install_path }}/conf/nginx.conf"

# nginx PID file path
nginx_pid_file_path: "{{ nginx_install_path }}/logs/nginx.pid"

# Number of simultaneous connections that can be opened by worker process
nginx_worker_connections: 4096

# Limit of the maximum number of open files for worker
nginx_worker_rlimit_nofile: 4096
