# Node.js has it's own repository. In order to have it available we need to add it to Yum repositories
#
- name: Make sure that Node.js repository is available
  template:
    src: nodesource-el7.repo.j2
    dest: /etc/yum.repos.d/datadog.repo
    owner: root
    group: root
    mode: 0644
  tags: [nodejs]



# Install Node.js and NPM
#
- name: Install Node.js and NPM
  yum:
    name: "nodejs-{{ nodejs_version }}"
    state: present
  tags: [nodejs]
