# Configure maximum size of internal in-memory temporary tables and maximum size of user-created MEMORY tables.
# Increase this value if you are doing lot of advanced GROUP BY queries
# Both tmp_table_size and max_heap_table_size should be set to equal values
#
- name: Configure tmp_table_size
  lineinfile:
    dest: "{{ mysql_config_file }}"
    line: "tmp-table-size={{ mysql_tmp_table_size }}"
    state: present
    insertbefore: EOF
    regexp: '^#?tmp-table-size'
  notify: restart mysqld
  tags: [mysql, configure]

- name: Configure max_heap_table_size
  lineinfile:
    dest: "{{ mysql_config_file }}"
    line: "max-heap-table-size={{ mysql_max_heap_table_size }}"
    state: present
    insertbefore: EOF
    regexp: '^#?max-heap-table-size'
  notify: restart mysqld
  tags: [mysql, configure]



# Configure query caching. First enable the cache, second, set the size of cache
#
- name: Configure query_cache_type
  lineinfile:
    dest: "{{ mysql_config_file }}"
    line: "query-cache-type={{ mysql_query_cache_type }}"
    state: present
    insertbefore: EOF
    regexp: '^#?query-cache-type'
  notify: restart mysqld
  tags: [mysql, configure]

- name: Configure query_cache_size
  lineinfile:
    dest: "{{ mysql_config_file }}"
    line: "query-cache-size={{ mysql_query_cache_size }}"
    state: present
    insertbefore: EOF
    regexp: '^#?query-cache-size'
  notify: restart mysqld
  tags: [mysql, configure]


#  [mysqld]
#
#
#   CACHES AND LIMITS #
#  thread-cache-size              = 50
#  open-files-limit               = 65535
#  table-definition-cache         = 1024
#  table-open-cache               = 2048
#
#   INNODB #
#  innodb-flush-method            = O_DIRECT
#  innodb-log-files-in-group      = 2
#  innodb-log-file-size           = 128M
#  innodb-flush-log-at-trx-commit = 1
#  innodb-file-per-table          = 1
#  innodb-buffer-pool-size        = 128M
#
#   LOGGING #
#  log-error                      = /var/lib/mysql/mysql-error.log
#  log-queries-not-using-indexes  = 1
#  slow-query-log                 = 1
#  slow-query-log-file            = /var/lib/mysql/mysql-slow.log
#
#
#
#
  ############# GENERATED #####################################
#   Generated by Percona Configuration Wizard (http://tools.percona.com/) version REL5-20120208
#   Configuration name server generated for astaz3l@gmail.com at 2016-11-22 14:45:31
#
#
#  [mysqld]
#
#
#   CACHES AND LIMITS #
#  thread-cache-size              = 50
#  open-files-limit               = 65535
#  table-definition-cache         = 1024
#  table-open-cache               = 2048
#
#   INNODB #
#  innodb-flush-method            = O_DIRECT
#  innodb-log-files-in-group      = 2
#  innodb-log-file-size           = 256M
#  innodb-flush-log-at-trx-commit = 1
#  innodb-file-per-table          = 1
#  innodb-buffer-pool-size        = 12G
#
#   LOGGING #
#  log-error                      = /var/lib/mysql/mysql-error.log
#  log-queries-not-using-indexes  = 1
#  slow-query-log                 = 1
#  slow-query-log-file            = /var/lib/mysql/mysql-slow.log
#
#
#   BINARY LOGGING #
#  log-bin                        = /var/lib/mysql/mysql-bin
#  expire-logs-days               = 14
#  sync-binlog                    = 1
#
#
#
#
#
#  mysqltuner on lightwidget.com
#      innodb_buffer_pool_size (>= 1G) if possible.
#      innodb_buffer_pool_instances (=1)


#2016-11-22T15:33:12.104540Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
#2016-11-22T15:33:12.206925Z 0 [Warning] CA certificate ca.pem is self signed.