# Check if MySQL server is installed or not and if it should be updated or not
#
- name: Check if MySQL is installed
  command: mysql --version warn=no
  register: mysql_is_installed_test
  ignore_errors: yes
  changed_when: false
  tags: [mysql]

- set_fact:
    mysql_is_installed: true
  when: mysql_is_installed_test.rc != 2
  tags: [mysql]

- set_fact:
    mysql_is_installed: false
    mysql_install_new_version: true
  when: mysql_is_installed_test.rc == 2
  tags: [mysql]

- set_fact:
    mysql_install_new_version: true
  when: ( mysql_is_installed == true ) and ( mysql_is_installed_test.stdout.split(',')[0].split(' ')[5] != mysql_version )
  tags: [mysql]

- set_fact:
    mysql_install_new_version: false
  when: ( mysql_is_installed == true ) and ( mysql_is_installed_test.stdout.split(',')[0].split(' ')[5] == mysql_version )
  tags: [mysql]



# Install/Update MySQL to desired version
# These tasks will be executed when
#  1. MySQL is not installed
#  2. MySQL is installed but not in desired version
#
- include: install.yml
  when: "mysql_install_new_version == true"
