mongodb_version: "3.4.0"

mongodb_manage_installation: yes

mongodb_manage_configuration: yes

mongodb_config_flie: /etc/mongod.conf

mongodb_process_fork: "false"

mongodb_pid_directory: /var/lib/mongo

mongodb_authorization: enabled

mongodb_admin_password: "alamakota"
