####### CHOOSE IF THIS ROLE SHOULD EXECUTE TASKS FROM GIVEN GROUPS #######

# Should this role use install tasks for compiling redis?
redis_manage_installation: yes

# Should this role use configure tasks for redis configuration?
redis_manage_configuration: yes





####### INSTALL TASKS CONFIGURATION #######

# Version of redis that should be present in the system
redis_version: "4.0.1"

# Location of files for redis sources
redis_sources_location: /usr/src

# User that will build redis. Please never use root account for compiling software. It can lead to serious security issues
redis_build_user: developer

# Group of the build user.
redis_build_group: developer

# Remove downloaded sources after installation
redis_cleanup_after_install: yes

# Redis config directory
redis_config_directory: /etc/redis




####### CONFIGURE TASKS CONFIGURATION #######

# redis.conf path
redis_conf_path: "{{ redis_config_directory }}/redis.conf"

# redis PID file path
redis_pid_file_path: "/var/run/redis.pid"

# Redis port
redis_port: 6379
