# Check if Apache HTTPD is installed or not and if it should be updated or not
#
- name: Check if Apache httpd is installed
  command: httpd --version warn=no
  register: httpd_is_installed_test
  ignore_errors: yes
  changed_when: false
  tags: [https]

- set_fact:
    httpd_is_installed: true
  when: httpd_is_installed_test.rc != 2
  tags: [git]

- set_fact:
    httpd_is_installed: false
    httpd_install_new_version: true
  when: httpd_is_installed_test.rc == 2
  tags: [git]

#- set_fact:
#    git_install_new_version: true
#  when: ( git_is_installed == true ) and ( git_is_installed_test.stdout | replace('git version ','') != git_version )
#  tags: [git]

#- set_fact:
#    git_install_new_version: false
#  when: ( git_is_installed == true ) and ( git_is_installed_test.stdout | replace('git version ','') == git_version )
#  tags: [git]



# Install/Update Apache httpd to desired version
# These tasks will be executed when
#  1. Apache httpd is not installed
#  2. Apache httpd is installed but not in desired version
#
- include: install.yml
  when: "httpd_is_installed == false"
