####### CHOOSE IF THIS ROLE SHOULD EXECUTE TASKS FROM GIVEN GROUPS #######

# Should this role use yum tasks for packages management?
centos_manage_yum: yes

# Should this role use groups tasks for linux groups management?
centos_manage_groups: yes

# Should this role use users tasks for linux users management?
centos_manage_users: yes

# Should this role use sudo tasks for linux sudoers file?
centos_manage_sudo: yes

# Should this role use ssh tasks for setting up secure SSH?
centos_manage_ssh: yes




####### YUM TASKS CONFIGURATION #######

# Path to file where Ansible should storage information about list of installed packages.
centos_yum_initial_package_list_path: /etc/yum/initial-packages-list

# List of packages that should be removed from the server
centos_yum_unnecessary_packages:
 - gssproxy # leave it if you are using GSSAPI
 - libgudev1 # allow to connect to WiFi, not necessary on the server
 - mariadb-libs # leave it if you plan to use MariaDB instead of MySQL
 - NetworkManager # dependencies: libgudev1
 - NetworkManager-libnm # dependencies: libgudev1
 - NetworkManager-tui # dependencies: libgudev1
 - NetworkManager-wifi # dependencies: libgudev1
 - postfix # leave it if you plan to use postfix for mails, dependencies: mariadb-libs

# List of core packages that should be updated to latest versions
centos_yum_core_packages:
 - bash
 - chkconfig
 - dbus
 - dbus-libs # dependencies: dbus
 - dracut
 - glibc
 - glibc-common # dependencies: glibc
 - kpartx
 - krb5-libs
 - libblkid
 - libmount # dependencies: libblkid
 - libuuid # dependencies: libblkid
 - libssh2
 - libxml2
 - nspr
 - nss
 - nss-softokn
 - nss-softokn-freebl
 - nss-sysinit
 - nss-tools
 - nss-util
 - openldap
 - openssl-libs
 - pcre
 - python
 - python-libs # dependencies: python
 - systemd
 - systemd-libs # dependencies: systemd
 - systemd-sysv # dependencies: systemd
 - util-linux # dependencies: libblkid
 - tzdata

# List of other packages that should be updated to latest versions
centos_yum_other_packages:
 - authconfig # dependencies: openssl
 - bind-libs-lite
 - bind-license # dependencies: bind-libs-lite, dhclient, dracut-network, kexec-tools
 - cronie
 - cronie-anacron # dependencies: cronie
 - crontabs # dependencies: cronie
 - device-mapper-persistent-data
 - dhclient # depenencies: bind-libs-lite
 - dracut-network # dependencies: dracut, iproute, dhclient, bind-libs-lite
 - dracut-config-rescue # dependencies: dracut
 - epel-release
 - iproute
 - initscripts
 - kbd # dependencies: iproute
 - kernel
 - kernel-tools
 - kernel-tools-libs # dependencies: kernel-tools
 - kexec-tools # dependencies: dhclient, bind-libs-lite
 - lvm2 # dependencies: device-mapper-persistent-data
 - microcode_ctl
 - openssh # dependencies: openssh-clients, openssh-server
 - openssh-clients
 - openssh-server
 - openssl
 - python-perf
 - selinux-policy
 - selinux-policy-targeted # depenency of selinux-policy
 - sudo
 - tuned # dependencies: python-perf

# List of additional tools that are missing from CentOS minimal installation but are super useful
centos_yum_additional_tools:
 - net-tools # add netstat tool





####### GROUPS TASKS CONFIGURATION #######

# Path to file where initial list of available groups is stored
centos_groups_initial_groups_list_path: /etc/initial-group-list

# List of groups to remove from the system
centos_groups_to_remove: []

# List of available groups in the system
# In www group we usually have all applications that writes to files like php, httpd etc.
centos_groups_available:
 - www





####### USERS TASKS CONFIGURATION #######

# Path to file where initial list of existing users is stored
centos_users_initial_users_list_path: /etc/initial-users-list

# List of users to remove from the system
centos_users_to_remove: []

# List of available users
# If you want to give sudo power to the user, add him to "wheel" group
# Password should NOT be stored in plain text. To make it secure you should override it variable file and encrypt it with Ansible Vault
# If generate_ssh_key is set to yes, user will have 4096 bit RSA key in his profile
centos_users_available:
  - {
      username: developer,
      groups: 'wheel,www',
      password: "{{ centos_users_developer_password }}",
      generate_ssh_key: yes
    }

# You can't use plain text user passwords with Ansible
# Password must by encrypted with crypt with following command:
# python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
# Make sure that you have passlib package installed ( sudo pip install passlib )
# Please remember to use Ansible Vault for keeping such credentials in a safe way
centos_users_developer_password: "$6$rounds=656000$DeNu.bf92WDgbQIW$olUwR2s0Oz92c/PFKdBSedZNJS80APVsFkxExoOACwMDMBrM7d.6DHSpx8wW7kBL3QLfCXSyf2O6MQj.sXUnN/"

# Authorised keys to add to user
# Path to file must be the path to your public key, not private!
centos_users_authorized_keys:
  - {
    username: developer,
    path_to_file: "{{ centos_users_developer_authorized_key_path }}"
  }


# To make it simpler to use in vars file, we extracted path to authorized key for developer account as separate variable
centos_users_developer_authorized_key_path: ~/.ssh/id_rsa.pub





####### SUDO TASKS CONFIGURATION #######

# Should wheel group use sudo with password or without password?
# Security recommendation is to set this variable to "yes"
centos_groups_wheel_password_required: yes





####### SSH TASKS CONFIGURATION #######

# Path to SSH config file
centos_ssh_config_file: /etc/ssh/sshd_config

# Turn on or off authentication with public key (valid values: "yes" | "no")
centos_ssh_authentication_public_key: "yes"

# Turn on or off authentication with passwords (valid values: "yes" | "no")
centos_ssh_authentication_password: "no"

# Turn on or off GSS API authentication (valid values: "yes" | "no")
centos_ssh_authentication_gss_api: "no"

# Turn on or off Kerberos authentication (valid values: "yes" | "no")
centos_ssh_authentication_kerberos: "no"

# Turn on or off logging in as root (valid values: "yes" | "no")
centos_ssh_login_as_root: "no"

# Turn on or off logging for users with empty password (valid values: "yes" | "no")
centos_ssh_login_with_empty_password: "no"

# Turn on or off strict mode
centos_ssh_strict_mode: "yes"

# List of users that are able to login via SSH. Leave it empty ( value:  [] )to turn this feature off (all users are able to login)
centos_ssh_allowed_users:
  - developer

# Turn on or off ignoring .rhosts and .shosts files (valid values: "yes" | "no")
centos_ssh_ignore_rhosts: "yes"

# Turn on or off X11 Forwarding (valid values: "yes" | "no")
centos_ssh_x11_forwarding: "no"