# Create php-fpm.conf file from .default version
# Right after the installation configuration for php-fpm is not present
#
- name: Create php-fpm.conf file if not present
  copy:
    src: "{{ php_install_path }}/etc/php-fpm.conf.default"
    dest: "{{ php_fpm_conf_file_path }}"
    remote_src: yes
    force: no
    owner: root
    group: root
    mode: 0644
  tags: [php, fpm]



# Set PHP-FPM pid file
# It is required for proper functioning of PHP-FPM with SystemD
#
- name: Configure PHP-FPM pid
  lineinfile:
    dest: "{{ php_fpm_conf_file_path }}"
    line: "pid = {{ php_pid_location }}"
    state: present
    regexp: '^;?pid'
  notify: restart php-fpm
  tags: [php, fpm]



# Setup FPM pools
# General rule is to have single pool per application/domain etc
#
- name: Create FPM pools
  template:
    src: fpm-pool.j2
    dest: "{{ php_install_path }}/etc/php-fpm.d/{{ item.name }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ php_fpm_pools }}"
  notify: restart php-fpm
  tags: [php, fpm]



# Add created FPM pools to php-fpm.conf and remove all others
#
- name: Add FPM pools to php-fpm.conf
  lineinfile:
    dest: "{{ php_fpm_conf_file_path }}"
    line: "include={{ php_install_path }}/etc/php-fpm.d/{{ item.name }}.conf"
    state: present
    insertafter: EOF
  with_items: "{{ php_fpm_pools }}"
  notify: restart php-fpm
  tags: [php, fpm]

- name: Remove all unused pools from php-fpm.conf file
  lineinfile:
    dest: "{{ php_fpm_conf_file_path }}"
    regexp: "php-fpm.d/(?!{{ php_fpm_pools | map(attribute='name') | join('|') }})"
    state: absent
  notify: restart php-fpm
  tags: [php, fpm]



# Setup logrotate for given FPM pools
#
- name: Setup logrotate for PHP-FPM
  template:
    src: logrotate.j2
    dest: "/etc/logrotate.d/php-fpm"
    owner: root
    group: root
    mode: 0644
  when: "php_fpm_logrotate == true"
  tags: [php, fpm, logrrr]
