# Check if PHP is installed or not and if it should be updated or not
# Setting PATH is required, because sometimes Ansible doesn't use /etc/profile.d data;/
#
- name: Check if PHP is installed
  command: php -v warn=no
  register: php_is_installed_test
  ignore_errors: yes
  changed_when: false
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ php_install_path }}/bin"
  tags: [php]

- set_fact:
    php_is_installed: true
  when: php_is_installed_test.rc != 2
  tags: [php]

- set_fact:
    php_is_installed: false
    php_install_new_version: true
  when: php_is_installed_test.rc == 2
  tags: [php]

- set_fact:
    php_install_new_version: true
  when: ( php_is_installed == true ) and ( php_is_installed_test.stdout_lines[0] | regex_replace('[^0-9.]','') != php_version )
  tags: [php]

- set_fact:
    php_install_new_version: false
  when: ( php_is_installed == true ) and ( php_is_installed_test.stdout_lines[0] | regex_replace('[^0-9.]','') == php_version )
  tags: [php]



# Install/Update PHP to desired version
# These tasks will be executed when
#  1. PHP is not installed
#  2. PHP is installed but not in desired version
#
- include: install.yml
  when: "php_install_new_version == true and php_manage_installation == true"
