# Make sure that OPcache is enabled
#
- name: Enable OPcache
  lineinfile:
    dest: "{{ php_ini_file_path }}"
    line: "opcache.enable = {{ php_opcache_enable }}"
    state: present
    regexp: '^;?opcache\.enable'
    insertafter: "[opcache]"
  notify: restart php-fpm
  tags: [php, opcache]



# Set shared memory storage consumption for OPcache
#
- name: Set memory consumption
  lineinfile:
    dest: "{{ php_ini_file_path }}"
    line: "opcache.memory_consumption = {{ php_opcache_memory_consumption }}"
    state: present
    regexp: '^;?opcache\.memory_consumption'
    insertafter: "[opcache]"
  notify: restart php-fpm
  tags: [php, opcache]



# Set amount of memory used to store interned strings
#
- name: Set interned strings buffer
  lineinfile:
    dest: "{{ php_ini_file_path }}"
    line: "opcache.interned_strings_buffer = {{ php_opcache_interned_strings_buffer }}"
    state: present
    regexp: '^;?opcache\.interned_strings_buffer'
    insertafter: "[opcache]"
  notify: restart php-fpm
  tags: [php, opcache]



# Set number of accelerated files by OPcache
#
- name: Set maximum number of accelerated files
  lineinfile:
    dest: "{{ php_ini_file_path }}"
    line: "opcache.max_accelerated_files = {{ php_opcache_accelerated_files }}"
    state: present
    regexp: '^;?opcache\.max_accelerated_files'
    insertafter: "[opcache]"
  notify: restart php-fpm
  tags: [php, opcache]



# Set timestamp validations for files
#
- name: Set timestamp validation
  lineinfile:
    dest: "{{ php_ini_file_path }}"
    line: "opcache.validate_timestamps = {{ php_opcache_validated_timestamps }}"
    state: present
    regexp: '^;?opcache\.validate_timestamps'
    insertafter: "[opcache]"
  notify: restart php-fpm
  tags: [php, opcache]
