# Restart yum-cron task
# This is usually executed on changes in yum-cron main configuration file
#
- name: restart yum-cron
  service:
    name: yum-cron
    state: restarted



# Restart sshd service
# This handler is executed on changes in sshd_config file
#
- name: restart sshd
  service:
    name: sshd
    state: restarted



# Reload iptables
# This handler is executed on changes in firewall rule-set
#
- name: reload firewall
  shell: "{{ item }}"
  with_items:
    - iptables-restore < /etc/sysconfig/firewall-rules
