####### MAIN TASKS CONFIGURATION #######

# Datadog key. It must be valid key
datadog_key: 37bd293b3418375da9349de40623a273

# Datadog hostname
datadog_hostname: example-hostname.com

# Datadog integrations directory
datadog_conf_path: /etc/dd-agent/conf.d





####### INTEGRATIONS TASKS CONFIGURATION #######

# List of enabled integrations
datadog_enabled_integrations:
 - apache
 - http_check
 - system_core

# Config for http_check integration
datadog_http_check_websites:
 - name: "Example website"
   url: http://example.com
   timeout: 4

# Url for checking apache server status
datadog_apache_status_url: http://127.0.0.1/server-status?auto
