# Make sure that EPEL release is available.
# It provides latest version of Certbot for obtaining certificates
#
- name: Install EPEL repository
  yum:
    name: epel-release
    state: latest
  tags: [letsencrypt]



# Install Certbot for obtaining certificates
#
- name: Install Certbot
  yum:
    name: certbot # Dependencies: dialog pyOpenSSL python-cffi python-enum34 python-idna python-ipaddress python-ndg_httpsclientpython-parsedatetime python-ply python-psutil python-pycparser python-requests python-six python-urllib3 python-zope-component python-zope-event python-zope-interface python2-acme python2-certbot python2-configargparsepython2-cryptography python2-dialog python2-mock python2-pyasn1 python2-pyrfc3339 pytz
    state: latest
  tags: [letsencrypt]



# Obtain certificates from Let's Encrypt
#
- name: Obtain certificates
  command: "certbot certonly --webroot --webroot-path {{ item.webroot_path }} --domains {{ item.domains }} --email {{ item.email_address }} {{ letsencrypt_certbot_certonly_arguments | join(' ') }}"
  args:
    creates: "/etc/letsencrypt/live/{{ item.domains }}"
  with_items: "{{ letsencrypt_domains }}"
  tags: [letsencrypt]



# Setup crontab for renewal process
# Certbot will check the certificates and will renew them whenever it's possible
#
- name: Setup crontab for certificates renewal
  cron:
    name: certbot renew
    minute: 1
    hour: 1
    job: "certbot renew --quiet"
  tags: [letsencrypt]
