php_install_path: /usr/local/php

php_version: "7.1.0"

php_force_install: no

php_manage_installation: yes

php_sources_location: /usr/src

php_build_user: developer

php_build_group: www

php_installation_path: /usr/local/php

php_ini_file_path: "{{ php_installation_path }}/lib/php.ini"

php_fpm_conf_file_path: "{{ php_installation_path }}/etc/php-fpm.conf"

# ./configure --prefix=/usr/local/php --enable-fpm --disable-short-tags --with-openssl --with-pcre-regex --with-pcre-jit --with-zlib --enable-bcmath \
#--with-bz2 --enable-calendar --with-curl --enable-exif --with-gd --enable-gd-native-ttf --enable-intl --enable-mbstring --with-mcrypt
php_configure_options:
 - "--prefix={{ php_installation_path }}"
 - --enable-fpm
 - --disable-short-tags
 - --with-openssl
 - --with-pcre-regex
 - --with-pcre-jit
 - --with-zlib
 - --enable-bcmath
 - --with-bz2
 - --enable-calendar
 - --with-curl
 - --enable-exif
 - --with-gd
 - --enable-gd-native-ttf
 - --enable-intl
 - --enable-mbstring
 - --with-mcrypt
 - --with-mysqli
 - --enable-pcntl
 - --with-pdo-mysql
 - --enable-soap
 - --enable-sockets
 - --with-xmlrpc
 - --enable-zip

php_cleanup_after_install: yes

php_manage_configuration: yes

php_short_open_tag: "Off"

php_expose_php: "Off"

php_max_execution_time: 30

php_max_input_time: 60

php_memory_limit: 128M

php_error_reporting: E_ALL

php_display_errors: "Off"

php_display_startup_errors: "Off"

php_log_errors: "On"

php_post_max_size: 8M

php_upload_max_filesize: 2M

php_allow_url_fopen: "On"

php_date_timezone: UTC

php_manage_fpm: yes

php_pid_location: run/php-fpm.pid

# Possible additional options
#  --with-webp-dir=DIR      GD: Set the path to libwebp install prefix
#  --with-jpeg-dir=DIR     GD: Set the path to libjpeg install prefix
#  --with-png-dir=DIR      GD: Set the path to libpng install prefix
#  --with-libdir=NAME      Look for libraries in .../NAME rather than .../lib

php_fpm_pools:
 - {
  name: www,
  user: developer,
  group: www,
  port: 9000,
  process_manager: {
    pm: dynamic,
    max_children: 5,
    start_servers: 2,
    min_spare_servers: 1,
    max_spare_servers: 3
  },
  slow_log: "var/log/$pool.log.slow",
  slow_log_timeout: 30s,
  php_admin_flags: [
    { key: log_errors, value: "On" }
  ],
  php_admin_values: [
      { key: error_log, value: /var/log/fpm-php.www.log },
      { key: open_basedir, value: /var },
      { key: disable_functions, value: "exec,passthru,shell_exec,system" }
    ],
 }

php_manage_extensions: yes

php_extensions:
  - mongodb
#  - mongo
  - redis

php_manage_composer: yes

php_mysql_socket: /var/lib/mysql/mysql.sock