php_install_path: /usr/local/php

php_version: "7.1.0"

php_manage_installation: yes

php_sources_location: /usr/src

php_build_user: vagrant

php_build_group: vagrant

php_installation_path: /usr/local/php

php_ini_file_path: "{{ php_installation_path }}/lib/php.ini"

# ./configure --prefix=/usr/local/php --enable-fpm --disable-short-tags --with-openssl --with-pcre-regex --with-pcre-jit --with-zlib --enable-bcmath \
#--with-bz2 --enable-calendar --with-curl --enable-exif --with-gd --enable-gd-native-ttf --enable-intl --enable-mbstring --with-mcrypt
php_configure_options:
 - "--prefix={{ php_installation_path }}"
 - --enable-fpm
 - --disable-short-tags
 - --with-openssl
 - --with-pcre-regex
 - --with-pcre-jit
 - --with-zlib
 - --enable-bcmath
 - --with-bz2
 - --enable-calendar
 - --with-curl
 - --enable-exif
 - --with-gd
 - --enable-gd-native-ttf
 - --enable-intl
 - --enable-mbstring
 - --with-mcrypt
 - --with-mysqli
 - --enable-pcntl
 - --with-pdo-mysql
 - --enable-soap
 - --enable-sockets
 - --with-xmlrpc
 - --enable-zip

php_cleanup_after_install: yes

php_manage_configuration: yes

php_short_open_tag: "Off"

php_expose_php: "Off"

php_max_execution_time: 30

php_max_input_time: 60

php_memory_limit: 128M

php_error_reporting: E_ALL

php_display_errors: "Off"

php_display_startup_errors: "Off"

php_log_errors: "On"

php_post_max_size: 8M

php_upload_max_filesize: 2M

php_allow_url_fopen: "Off"

php_date_timezone: UTC

# Possible additional options
#  --with-webp-dir=DIR      GD: Set the path to libwebp install prefix
#  --with-jpeg-dir=DIR     GD: Set the path to libjpeg install prefix
#  --with-png-dir=DIR      GD: Set the path to libpng install prefix
#  --with-libdir=NAME      Look for libraries in .../NAME rather than .../lib

